version: '3.8'

services:
  telegram-bot:
    build: .
    env_file:
      - .env
    container_name: telegram-cra-bot
    depends_on:
      - postgres-db
    restart: unless-stopped

  postgres-db:
    image: postgres:15
    container_name: telegram-postgres
    environment:
      POSTGRES_DB: telegramdb
      POSTGRES_USER: telegramuser
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
