version: "3.8"

services:
  bot-service:
    build: .
    env_file:
      - .env
    container_name: bot-service
    depends_on:
      - db-service
    restart: unless-stopped

  db-service:
    image: postgres:15
    container_name: db-service
    environment:
      POSTGRES_DB: telegramdb
      POSTGRES_USER: telegramuser
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
